package entity;

import java.io.Serializable;
import lombok.Data;

/**
 * @TableName t_user
 */
@Data
public class User implements Serializable {
    /**
     * 
     *
     * @mbg.generated Wed Jan 06 13:54:20 CST 2021
     */
    private Long id;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 13:54:20 CST 2021
     */
    private String loginname;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 13:54:20 CST 2021
     */
    private String loginpwd;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 13:54:20 CST 2021
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Wed Jan 06 13:54:20 CST 2021
     */
    private static final long serialVersionUID = 1L;
}